version: "3"
services:
  db:
    container_name: db01
    image: postgres
    volumes:
      - dbdata:/pgdata
    env_file: db/env_db
  django:
    container_name: project01
    build: webapp/
    volumes:
      - webapp:/webapp
      - static_volume:/webapp/static  # <-- bind the static volume
      - media_volume:/webapp/media  # <-- bind the media volume
    depends_on: 
      - db 
    links:
      - redis
  redis:
    image: redis:latest
    container_name: cache01
    ports:
      - "6379:6379"
  nginx:
    container_name: nginx01
    image: nginx
    volumes:
      - ./serv/:/etc/nginx/conf.d
      - static_volume:/webapp/static  # <-- bind the static volume
      - media_volume:/webapp/media  # <-- bind the media volume
    ports:
      - "8000:80"
      - "443:443"
    links:
      - django:django
    depends_on:
      - django
volumes:
  dbdata:
  webapp:
  static_volume:
  media_volume: